# Generated by Django 5.2 on 2025-04-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
